name: boilerplate
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # UI
  quickui: ^1.1.0
  gif: ^2.3.0
  flutter_svg: ^2.0.0
  gap: ^3.0.1
  flutter_screenutil: ^5.9.0
  lottie: ^3.1.0

  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2

  # State Management & Navigation
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1

  # Utility
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_dotenv: ^5.1.0
  sentry_flutter: ^7.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.2
  flutter_launcher_icons: "^0.13.1"
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/image/app_launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - asset/.env
    - asset/image/
    - asset/icon/
    - asset/illustration/
    - asset/animation/
    - asset/gif/

  fonts:
    - family: proximaNova
      fonts:
        - asset: 'asset/font/Proxima Nova Light.otf'
          weight: 300
        - asset: 'asset/font/Proxima Nova Light Italic.otf'
          weight: 300
          style: italic
        - asset: 'asset/font/Proxima Nova Regular.otf'
          weight: 400
        - asset: 'asset/font/Proxima Nova Regular Italic.otf'
          weight: 400
          style: italic
        - asset: 'asset/font/Proxima Nova SemiBold.otf'
          weight: 600
        - asset: 'asset/font/Proxima Nova SemiBold Italic.otf'
          weight: 600
          style: italic
        - asset: 'asset/font/Proxima Nova Bold.otf'
          weight: 700
        - asset: 'asset/font/Proxima Nova Bold Italic.otf'
          weight: 700
          style: italic